apiVersion: v1
kind: Pod
metadata:
  name: project-plt-6cc-api
  namespace: pluto
  labels:
    project: plt-6cc-api
spec:
  containers:
  - name: nginx
    image: nginx:1.17.3-alpine
    ports:
    - containerPort: 80

