apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-v1
  namespace: production
spec:
  replicas: 5 
  selector:
    matchLabels:
      app: webapp        # <--- SHARED (Matches Service)
      version: v1        # <--- UNIQUE (Matches Template)
  template:
    metadata:
      labels:
        app: webapp      # <--- Service looks for this!
        version: v1
    spec:
      containers:
      - name: nginx
        image: nginx:1.14