apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"webapp-v1","namespace":"production"},"spec":{"replicas":5,"selector":{"matchLabels":{"app":"webapp","version":"v1"}},"template":{"metadata":{"labels":{"app":"webapp","version":"v1"}},"spec":{"containers":[{"image":"nginx:1.14","name":"nginx"}]}}}}
  creationTimestamp: "2026-01-18T16:43:38Z"
  generation: 2
  name: webapp-v2
  namespace: production
  resourceVersion: "44827"
  uid: 9a925bca-209f-4d2b-b653-35d86dc67b23
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: webapp
      version: v2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp
        version: v2
    spec:
      containers:
      - image: nginx:1.16
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 8
  conditions:
  - lastTransitionTime: "2026-01-18T16:43:38Z"
    lastUpdateTime: "2026-01-18T16:43:39Z"
    message: ReplicaSet "webapp-v1-6c4d84f8bf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2026-01-18T16:45:01Z"
    lastUpdateTime: "2026-01-18T16:45:01Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 8
  replicas: 8
  updatedReplicas: 8
