apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-v1
  namespace: production
spec:
  replicas: 5              # 4 Replicas (80% of total 5)
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp        # Shared Label
        version: v1
    spec:
      containers:
      - name: webapp
        image: nginx:1.21
        ports:
        - containerPort: 80