---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: broken-app
spec:
  replicas: 2 # update the replicas count
  selector:
     matchLabels:
      app: myapp
  template:  # Missing selector
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: web
          image: nginx