apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2026-01-18T14:27:34Z"
    generation: 1
    labels:
      run: log-collector
    name: log-collector
    namespace: audit
    resourceVersion: "29774"
    uid: 7ec5b4c7-4e10-4745-aa68-b4f546caec65
  spec:
    serviceAccountName: log-sa # Add this identity SA
    containers:
    - command:
      - /bin/sh
      - -c
      - while true; do echo 'Checking permissions...'; kubectl get pods; sleep 5;
        done
      image: bitnami/kubectl:latest
      imagePullPolicy: Always
      name: log-collector
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-w6qzd
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: 133-worker3
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-w6qzd
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-01-18T14:28:07Z"
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-01-18T14:27:34Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-01-18T14:28:07Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-01-18T14:28:07Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-01-18T14:27:34Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://59968bb32138a1f644f824b044d6cebd8265e4e721d356e33cc2a68332260946
      image: docker.io/bitnami/kubectl:latest
      imageID: docker.io/bitnami/kubectl@sha256:b349e60a6ae2969af84a778c0b976b050a0cc77f4fb6a4ad44307cd0a06e9d8f
      lastState: {}
      name: log-collector
      ready: true
      resources: {}
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-01-18T14:28:06Z"
      user:
        linux:
          gid: 0
          supplementalGroups:
          - 0
          uid: 1001
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-w6qzd
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 172.18.0.5
    hostIPs:
    - ip: 172.18.0.5
    phase: Running
    podIP: 10.253.2.5
    podIPs:
    - ip: 10.253.2.5
    qosClass: BestEffort
    startTime: "2026-01-18T14:27:34Z"
kind: List
metadata:
  resourceVersion: ""
